### ISSUE TITLE
[ASK] About bot

### ISSUE THREAD

**Issue by leonyonz** [rctz/rok_title_bot#2]
Is it auto scrolling duke chat ? 

And how much interval per request ?

**Comment by rctz** [comment]
1. Yes it is auto scrolling duke chat.
2.  Default value is 2.75 minutes per request. You can set in [https://github.com/rctz/rok_title_bot/blob/master/config.ini](url)

**Comment by leonyonz** [comment]
@rctz Thank you for the explanation.

Anyway, is this project still continue or not ?

**Comment by rctz** [comment]
@leonyonz Yes, This project still continue. You can get development version from [https://github.com/rctz/rok_title_bot/tree/dev](url) or released version from [https://github.com/rctz/rok_title_bot/releases](url)
